ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_differential: false

    navsat0: /odometry/gps
    navsat0_config: [true, true, false,
                     false, false, false,
                     false, false, false,
                     false, false, false,
                     false, false, false]
    navsat0_differential: false
